In [42]:
import numpy as np

In [43]:
#create an array from a list
arr=np.array([1,2,2,3,4,5])
print (arr)

[1 2 2 3 4 5]


In [44]:
#arange function
#create an with regular spaced values

a_range=np.arange(0,10,2)
print(a_range)

[0 2 4 6 8]


In [45]:
#CREATE an array with evenly spaced values
a_linespace=np.linspace(0,10,5)
print(a_linespace)

[ 0.   2.5  5.   7.5 10. ]


In [46]:

random_uniform=np.random.rand(5)
print(random_uniform)

[0.74618364 0.91257094 0.79058803 0.70780108 0.97929438]


In [47]:
random_normal=np.random.randn(10)
print(random_normal)

[-0.12981749  0.26138006  0.62547577 -0.02456232 -0.81538348  0.43530036
  0.47728517 -0.36296799 -1.00269989 -0.54493338]


In [50]:
arr=np.array([[5,9,7],[9,5,4]])
shape=np.shape(arr)
#dtype=np.dtype(arr #int64)
size=np.size(arr)
print(shape)
print(size)
print(arr)

(2, 3)
6
[[5 9 7]
 [9 5 4]]


In [51]:
a=np.array([1,5,8,7,9,6,3,2,1])
first_element=a[0]
print(first_element)
slice_array=a[1:4]
print(slice_array)

1
[5 8 7]


In [53]:
#reshaping and manipulating array
arr=np.array([[1,2,3],[4,5,6]])
reshaped_arr=np.reshape(arr,(3,2))
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [54]:
transposed_arr=np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [55]:
#filtering
a=np.array([1,2,5,6,4,7,9,7])
filtering_arr=a[a>2]
print(filtering_arr)

[5 6 4 7 9 7]
