In [1]:
import numpy as np

In [2]:
#create an array from a list
arr=np.array([1,2,2,3,4,5])
print (arr)

[1 2 2 3 4 5]


In [3]:
#arange function
#create an with regular spaced values

a_range=np.arange(0,10,2)
print(a_range)

[0 2 4 6 8]


In [4]:
#CREATE an array with evenly spaced values
a_linespace=np.linspace(0,10,5)
print(a_linespace)

[ 0.   2.5  5.   7.5 10. ]


In [5]:

random_uniform=np.random.rand(5)
print(random_uniform)

[0.01739251 0.73556729 0.89896013 0.90804041 0.56971478]


In [6]:
random_normal=np.random.randn(10)
print(random_normal)

[ 0.31393282  0.52937476  0.070907    0.72803942 -0.10813923  1.47682706
  1.07324129 -0.34374371  0.19360677  2.12082771]


In [7]:
arr=np.array([[5,9,7],[9,5,4]])
shape=np.shape(arr)
#dtype=np.dtype(arr #int64)
size=np.size(arr)
print(shape)
print(size)
print(arr)

(2, 3)
6
[[5 9 7]
 [9 5 4]]


In [8]:
a=np.array([1,5,8,7,9,6,3,2,1])
first_element=a[0]
print(first_element)
slice_array=a[1:4]
print(slice_array)

1
[5 8 7]


In [9]:
#reshaping and manipulating array
arr=np.array([[1,2,3],[4,5,6]])
reshaped_arr=np.reshape(arr,(3,2))
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
transposed_arr=np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
#filtering
a=np.array([1,2,5,6,4,7,9,7])
filtering_arr=a[a>2]
print(filtering_arr)

[5 6 4 7 9 7]


TRIGNOMETRY 


LOGICAL 

In [18]:
#boolean filter
a[a > 5]

array([6, 7, 9, 7])

In [25]:
x=np.random.randint(-3,3,(5,5))
x

array([[ 2,  1,  2, -3, -3],
       [-2, -1,  0,  1,  1],
       [ 0, -3, -3, -2,  2],
       [-3,  0,  1,  2, -1],
       [ 1,  2,  1, -3, -1]])

In [32]:
x[(x>-2) & (x<=1) ] 
#x<=1

array([ 1, -1,  0,  1,  1,  0,  0,  1, -1,  1,  1, -1])

In [34]:
# indexing and slicing 
x[0][0]
x[0,0]

2

In [39]:
x[3,3]

x[3,7]

x[3,3]

IndexError: index 7 is out of bounds for axis 1 with size 5

In [40]:
print(x[0])# first row
print(x[-1])# last row

[ 2  1  2 -3 -3]
[ 1  2  1 -3 -1]


syntax for slicing in 1d:[start:stop:step]
syntax for slicing in 2d:[Rstart:Rstop:RStep , Cstart:Cstop:Cstep]


In [41]:
print(x[0,:3])

[2 1 2]


In [48]:
print([2,-4])
print(x[-1])#last row

[2, -4]
[ 1  2  1 -3 -1]


In [60]:
print(x[:,0]) #
print(x[:,:2]) #first two
print("r")
print(x[:,[1,3]]) #first index and third index and whole row
 

[ 2 -2  0 -3  1]
[[ 2  1]
 [-2 -1]
 [ 0 -3]
 [-3  0]
 [ 1  2]]
r
[[ 1 -3]
 [-1  1]
 [-3 -2]
 [ 0  2]
 [ 2 -3]]


In [65]:
# sorting
x.sort(axis=0)
x

array([[-3, -3, -3, -3, -3],
       [-3, -2, -1, -1,  0],
       [-2, -1,  0,  0,  1],
       [ 1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2]])

In [72]:
x=np.random.randint(1,100,(6,3))
x

array([[32, 88, 49],
       [14, 67, 99],
       [11, 38, 28],
       [84, 68, 32],
       [63, 43, 90],
       [75, 77, 27]])

In [73]:
x.sort(axis=0)
x

array([[11, 38, 27],
       [14, 43, 28],
       [32, 67, 32],
       [63, 68, 49],
       [75, 77, 90],
       [84, 88, 99]])

In [79]:
e=x.flatten()
x
e

array([11, 38, 27, 14, 43, 28, 32, 67, 32, 63, 68, 49, 75, 77, 90, 84, 88,
       99])

In [86]:
y=e.reshape(6,3)
y

array([[11, 38, 27],
       [14, 43, 28],
       [32, 67, 32],
       [63, 68, 49],
       [75, 77, 90],
       [84, 88, 99]])

In [87]:
x.max()

99

In [89]:
x.argmax()
x.argmin()

0

In [90]:
x

array([[11, 38, 27],
       [14, 43, 28],
       [32, 67, 32],
       [63, 68, 49],
       [75, 77, 90],
       [84, 88, 99]])